### ISSUE TITLE
BootStrap spanning problem.

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Joomla-Bible-Study#399]
Right now the way the spanning is generated it dos not account for the a full span12.

like fore span1 do not = span12

We need to change to a calculated spanning system.

**Comment by bcordis** [comment]
Ok so we need to make up a statement to have after installation to have them go and reconfigure there span's we can now use the post installation system in Joomla.

**Comment by bcordis** [comment]
We need to fix the example code to use the spans correctly. Right now we use only span1 and need to us span4 and so on to make it look right.

**Comment by tomfuller2** [comment]
I guess I figured they'd set that when they first go in. But no where are we explaining the new system. I was thinking that our help system on the website would provide that. What do you think?

**Comment by bcordis** [comment]
Yes are website should go into detail but we do need to make a statement to that fact that the template system has changed.

**Comment by tomfuller2** [comment]
Do you know how to implement that?
Here is some suggested language:
Version 9.x of Joomla Bible Study uses the native Bootstrap system to create responsive views. In order to implement this on your website, go to Templates and open the default record. Set spans in the items to display according to how wide you want them. Span1 is 1/12 of the width of the screen; Span12 is the entire width.

Also - when I use Phing to build the package - the component comes out at 10mb. I'm sure that's not right.

**Comment by st-anton** [comment]
As written in #438 the postinstall messages cannot be used currently to put a message. Either the postinstall comonent needs to be hacked or the language file needs to be placed in the CORE language folder.

**Comment by bcordis** [comment]
@st-anton did the language hack in the template.php file not work?

**Comment by st-anton** [comment]
No :-))
I got it! There's a simple reason, why it does not work: The installer scipt does not install the postinstall folder - and therefor no template.php is present.
Please add the folder in \com_biblestudy\biblestudy.xml

**Comment by bcordis** [comment]
@st-anton see fix for postinstall in the xml file 094c6f2971ec6b19d13cb87a48606d7f37da6175

**Comment by bcordis** [comment]
closing as fixed we have a solution.
